### ISSUE TITLE
Install issue with Git-lfs for SmartSim 0.3.2

### ISSUE THREAD

**Issue by jedwards4b** [CrayLabs/SmartSim#80]
# Description

When installing with pip the package git-lfs is not identified as a prereq:
```
pip install --no-cache-dir smartsim
Collecting smartsim
  Downloading smartsim-0.3.2-cp37-cp37m-manylinux2010_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 19.6 MB/s 
Requirement already satisfied: pandas>=1.1.3 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from smartsim) (1.1.5)
Collecting coloredlogs==10.0
  Downloading coloredlogs-10.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 69.9 MB/s 
Collecting redis==3.5.3
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 32.8 MB/s 
Requirement already satisfied: tqdm>=4.50.2 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from smartsim) (4.54.1)
Requirement already satisfied: toml>=0.10.1 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from smartsim) (0.10.2)
Collecting redis-py-cluster==2.1.3
  Downloading redis_py_cluster-2.1.3-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 48.4 MB/s 
Requirement already satisfied: psutil>=5.7.2 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from smartsim) (5.8.0)
Requirement already satisfied: numpy>=1.18.2 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from smartsim) (1.18.5)
Collecting smartredis>=0.1.1
  Downloading smartredis-0.2.0-cp37-cp37m-manylinux2010_x86_64.whl (393 kB)
     |████████████████████████████████| 393 kB 104.3 MB/s 
Collecting humanfriendly>=4.7
  Downloading humanfriendly-9.2-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 91.7 MB/s 
Requirement already satisfied: pytz>=2017.2 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from pandas>=1.1.3->smartsim) (2020.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from pandas>=1.1.3->smartsim) (2.8.1)
Requirement already satisfied: six>=1.5 in /glade/work/jedwards/casper_npl_clone2/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.3->smartsim) (1.15.0)
Installing collected packages: redis, humanfriendly, smartredis, redis-py-cluster, coloredlogs, smartsim
Successfully installed coloredlogs-10.0 humanfriendly-9.2 redis-3.5.3 redis-py-cluster-2.1.3 smartredis-0.2.0 smartsim-0.3.2
```

and an error is presented when you run:
```
 smart --device gpu

Backends Requested
-------------------
    PyTorch: True
    TensorFlow: True
    ONNX: False


Running SmartSim build process...
Traceback (most recent call last):
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 424, in <module>
    cli()
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 421, in cli
    builder.run_build(args.device, pt, tf, onnx)
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 83, in run_build
    self.check_prereq("git-lfs")
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 217, in check_prereq
    f"{command} must be installed to build SmartSim") from None
__main__.SetupError: git-lfs must be installed to build SmartSim
```
however even after installing the git-lfs module an error is still generated:
```
 pip install git-lfs
Collecting git-lfs
  Downloading git_lfs-1.6-py2.py3-none-any.whl (5.6 kB)
Installing collected packages: git-lfs
Successfully installed git-lfs-1.6

 smart --device gpu

Backends Requested
-------------------
    PyTorch: True
    TensorFlow: True
    ONNX: False


Running SmartSim build process...
Traceback (most recent call last):
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 424, in <module>
    cli()
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 421, in cli
    builder.run_build(args.device, pt, tf, onnx)
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 83, in run_build
    self.check_prereq("git-lfs")
  File "/glade/work/jedwards/casper_npl_clone2/bin/smart", line 217, in check_prereq
    f"{command} must be installed to build SmartSim") from None
__main__.SetupError: git-lfs must be installed to build SmartSim
```

# How to reproduce
The above install process should be followed

# Expected behavior

# System
 - OS: Linux casper-login2 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - OS version:
 - Commit/version of library:
 - Workload manager (e.g. PBS, Slurm): pbs
 - Workload manager version:2021.1.1.20210518090504

**Comment by Spartee** [comment]
Hi @jedwards4b, before you re-run the command, have you tried running ``git-lfs install``?

**Comment by jedwards4b** [comment]
I think that we should just close this issue and I'll try again from scratch.
